### ISSUE TITLE
Add tags to metrics

### ISSUE THREAD

**Issue by scaytrase** [lamoda/php-metrics#1]
Open questions:
 - [ ] Propagation to groups for formats without metric-level tags
 - [ ] Structure ( `string[]` ? )
 - [ ] Should tagging replace groups (i.e. with `group by tag` feature) for group aware formats (httpjson) ?

**Comment by omnilight** [comment]
Tag is not just string, it is key=value structure. Look like it implemented here: https://github.com/influxdata/telegraf/blob/master/metric/metric.go#L14

**Comment by scaytrase** [comment]
The problem of complex tags is comparision issue, but we can improve it, yes
