### ISSUE TITLE
Create simplifying facade for adjustable metrics

### ISSUE THREAD

**Issue by scaytrase** [lamoda/php-metrics#3]
Current interface is overcomplicated, so a facade interface like `adjust(string $key, float $delta)` could be used instead.

To simplify configuration we can also invent the `AdjustableMetricsFactoryInterface` to allow creating missing metrics on the fly

**Comment by omnilight** [comment]
Better to have not only `adjust`, but also `set`, because this is also very frequent to just set metric to some value, instead of changing it

**Comment by scaytrase** [comment]
Yes, I've already thought about it in 2.0
