### ISSUE TITLE
doctrine:schema:validate reports error

### ISSUE THREAD

**Issue by HaiD84** [lamoda/php-metrics#4]
Using bundle with Symfony 4:

```
$ ./bin/console doctrine:schema:validate

Mapping
-------

 [FAIL] The entity-class Lamoda\MetricBundle\Entity\MetricGroup mapping is invalid:
 * The target entity 'Lamoda\MetricResponder\MetricInterface' specified on Lamoda\MetricBundle\Entity\MetricGroup#metrics is unknown or not an entity.
```

**Comment by scaytrase** [comment]
@HaiD84 You have to point doctrine how to resolve `MetricInterface` into final entity as it's possible to use custom entitiies with built-in group and vice-versa

See the docs for reference

http://symfony.com/doc/current/doctrine/resolve_target_entity.html

**Comment by scaytrase** [comment]
We are going to cancel supporting groups in favour of dynamic metric grouping, i.e by tags, since not every format supports grouping and tags are first level citizen here (#1)

**Comment by omnilight** [comment]
And this is correct decision, voting for it

**Comment by scaytrase** [comment]
As for 2.0 metric doctrine entity implemnation if up to end user, so there is nothing to do with schema validation
